
set nocompatible

set showcmd

filetype on
filetype plugin on
syntax enable
color elflord
set grepprg=grep\ -nH\ $*

set autoindent

" Line numbers
set number

" Incremental search
set incsearch

" Highlight search matches
set hlsearch

set colorcolumn=80
highlight ColorColumn ctermbg=lightgrey guibg=lightgrey

filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab

set whichwrap+=<,>

set backspace=indent,eol,start

set statusline+=%f
set statusline+=%=%l/%L

set laststatus=2

set cursorline
hi CursorLine cterm=None ctermbg=black

